branch-defaults:
  develop:
    environment: webapp-dev
    group_suffix: null
  master:
    environment: CcbdaWebSimulator-env
    group_suffix: null
environment-defaults:
  CcbdaWebSimulator-env:
    branch: null
    repository: null
global:
  application_name: webapp
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
